version: 11.3.0.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
init:
- cmd: nuget sources add -Name Episerver -Source http://nuget.episerver.com/feed/packages.svc/
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
pull_requests:
  do_not_increment_build_number: true
build:
  publish_nuget: true
  verbosity: minimal
cache:
  - packages -> **\packages.config

for:
  branches:
    only:
      - master

    before_package:
    - ps: >-
        cd $env:APPVEYOR_BUILD_FOLDER\src\Epinova.ElasticSearch.Core.EPiServer;

        (Get-Content Epinova.ElasticSearch.Core.EPiServer.nuspec) -replace '\[11\.2.*12\)', $env:APPVEYOR_BUILD_VERSION | Out-File Epinova.ElasticSearch.Core.EPiServer.nuspec


        cd $env:APPVEYOR_BUILD_FOLDER\src\Epinova.ElasticSearch.Core.EPiServer.Commerce;

        (Get-Content Epinova.ElasticSearch.Core.EPiServer.Commerce.nuspec) -replace '\[11\.2.*12\)', $env:APPVEYOR_BUILD_VERSION | Out-File Epinova.ElasticSearch.Core.EPiServer.Commerce.nuspec

    deploy:
      provider: NuGet
      api_key:
        secure: /L7BuZN2mNqeHYM5tnD8Lyh5j+k/nd3vuurOt4zYwmCGTKcGvEo3afO0MWOTj5Yn
      skip_symbols: false
      artifact: /.*\.nupkg/