version: 11.7.1.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
environment:
  sonarcloudorg: epinova
  sonarcloudproj: Epinova_Epinova.Elasticsearch
  sonarcloudkey:
    secure: 0VvcxYCPLglmyB87e5B1vRk0nHq8KUX0ND/qLkCs1RaGULzo1Q+XPHOZgioTbEPZ
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
- ps: >-
    If ("$env:sonarcloudkey".Length -gt 0) {
      choco install sonarscanner-msbuild-net46 opencover.portable -y
      SonarScanner.MSBuild.exe begin /k:"%sonarcloudproj%" /d:"sonar.host.url=https://sonarcloud.io" /o:"%sonarcloudorg%" /d:"sonar.branch.name=%APPVEYOR_REPO_BRANCH%" /d:"sonar.login=%sonarcloudkey%" /d:sonar.cs.opencover.reportsPaths="%APPVEYOR_BUILD_FOLDER%\xunit.opencover.results.xml" /d:sonar.cs.xunit.reportsPaths="%APPVEYOR_BUILD_FOLDER%\xunit.test.results.xml"
    }
after_test:
- cmd: IF DEFINED sonarcloudkey SonarScanner.MSBuild.exe end /d:"sonar.login=%sonarcloudkey%"
pull_requests:
  do_not_increment_build_number: true
build:
  publish_nuget: true
  verbosity: minimal
test_script:
- cmd: 'OpenCover.Console.exe -register:user -returntargetcode -target:"%xunit20%\xunit.console.exe" -targetargs:"tests\Core.Tests\bin\Core.Tests.dll tests\Core.Episerver.Tests\bin\Core.Episerver.Tests.dll -noshadow -xml %APPVEYOR_BUILD_FOLDER%\xunit.test.results.xml -appveyor" -output:%APPVEYOR_BUILD_FOLDER%\xunit.opencover.results.xml -coverbytest:*Tests.dll'
artifacts:
- path: '%APPVEYOR_BUILD_FOLDER%\xunit.test.results.xml'
- path: '%APPVEYOR_BUILD_FOLDER%\xunit.opencover.results.xml'
cache:
  - packages -> **\packages.config
  - '%USERPROFILE%\.nuget\packages'
  - C:\ProgramData\chocolatey\bin-> appveyor.yml
  - C:\ProgramData\chocolatey\lib-> appveyor.yml
before_package:
- ps: >-
    cd $env:APPVEYOR_BUILD_FOLDER\src\Epinova.ElasticSearch.Core.EPiServer;
    (Get-Content Epinova.ElasticSearch.Core.EPiServer.nuspec) -replace '\[11\.2.*12\)', $env:APPVEYOR_BUILD_VERSION | Out-File Epinova.ElasticSearch.Core.EPiServer.nuspec;
    cd $env:APPVEYOR_BUILD_FOLDER\src\Epinova.ElasticSearch.Core.EPiServer.Commerce;
    (Get-Content Epinova.ElasticSearch.Core.EPiServer.Commerce.nuspec) -replace '\[11\.2.*12\)', $env:APPVEYOR_BUILD_VERSION | Out-File Epinova.ElasticSearch.Core.EPiServer.Commerce.nuspec;
    cd $env:APPVEYOR_BUILD_FOLDER;

for:
-
  branches:
    only:
      - vnext

  init:
  - ps: >-
      Update-AppveyorBuild -Version "$env:APPVEYOR_BUILD_VERSION-$env:APPVEYOR_REPO_BRANCH";
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }

  deploy:
    provider: NuGet
    api_key:
      secure: M+b7dlgbK5GWibG7RSV5AtkA4EkVGF6+RC49j5bVeJwTbKxKgSkeEiE60J4uYEVf
    skip_symbols: false
    artifact: /.*\.nupkg/

-
  branches:
    only:
      - master

  deploy:
    provider: NuGet
    api_key:
      secure: M+b7dlgbK5GWibG7RSV5AtkA4EkVGF6+RC49j5bVeJwTbKxKgSkeEiE60J4uYEVf
    skip_symbols: false
    artifact: /.*\.nupkg/
